server:
  port : 8081
camunda.bpm.client:
  base-url: http://localhost:8080/engine-rest
  lock-duration: 10000
  subscriptions:
    check-addresses:
      variable-names: [_from, _to, _tokenId, _contractAddress, _tokenUri, _price]
      process-definition-key: transfer-nft-exception-handle
    manage-contract:
      variable-names: [_from, _to, _tokenId, _contractAddress, _tokenUri]
      process-definition-key: transfer-nft-exception-handle
    manage-token:
      variable-names: [_from, _to, _tokenId, _contractAddress, _tokenUri]
      process-definition-key: transfer-nft-exception-handle
    approve-transfer:
      variable-names: [_from, _to, _tokenId, _contractAddress, _tokenUri]
      process-definition-key: transfer-nft-exception-handle
    transfer-nft:
      variable-names: [_from, _to, _tokenId, _contractAddress, _tokenUri]
      process-definition-key: transfer-nft-exception-handle
    address-error:
      process-definition-key: transfer-nft-exception-handle
    token-error:
      process-definition-key: transfer-nft-exception-handle



